name: Deploy Vitepress and Live Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and install pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm ci
      - name: Build docs & live demo
        run: pnpm run build:pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
